name: tix
version: 0.1.0.0
github: "ilyakooo0/tix"
license: BSD3
author: "Ilya Kostyuchenko"
maintainer: "ilyakooo0@gmail.com"
copyright: "2020 Ilya Kostyuchenko"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ilyakooo0/tix#readme>

dependencies:
  - base >= 4.7 && < 5
  - freer-simple
  - hnix
  - containers
  - text
  - lens
  - data-fix
  - mono-traversable
  - acts
  - groups
  - yaml
  - aeson
  - vector
  - unordered-containers
  - bytestring
  - prettyprinter
  - range-set-list
  - generic-data
  - generic-lens

library:
  source-dirs: src

executables:
  tix-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tix

tests:
  tix-test:
    main: Main.hs
    source-dirs: test/src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - tix
      - tasty
      - tasty-golden
      - filepath

default-extensions:
  - GADTs
  - FlexibleContexts
  - ScopedTypeVariables
  - TypeOperators
  - DataKinds
  - RankNTypes
  - TypeApplications
  - LambdaCase
  - OverloadedStrings
  - DeriveFunctor
  - DerivingStrategies
  - GeneralizedNewtypeDeriving
  - UndecidableInstances
  - PatternSynonyms
  - ViewPatterns
  - KindSignatures
  - MultiParamTypeClasses
  - TupleSections
  - EmptyDataDeriving
  - EmptyCase
  - OverloadedLists
  - StandaloneDeriving
  - DeriveGeneric
  - DerivingVia
  - RecordWildCards
  - FunctionalDependencies
  - DeriveDataTypeable
  - TypeFamilies
  - FlexibleInstances
  - DeriveAnyClass
  - ConstraintKinds
