name: Build docs
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Build docs
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    steps:
      - uses: actions/checkout@v1
      - uses: cachix/install-nix-action@v12
      - name: Create /nix/store
        run: |
          sudo rm -rf /nix/store
          sudo mkdir -p /nix/store
          sudo chown --verbose "$USER:" /nix/store
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            /nix/store
          key: ${{ runner.os }}-nix
      - name: Build
        id: build
        run: |
          mkdir res
          for f in $(nix-build)
          do
            cp $f/*.pdf res
          done
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: res/*.pdf
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "docs_latest"
          # prerelease: true
          title: "Docs"
          files: |
            res/*.pdf
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
