name: Build docs
on:
  push:
    branches:
      - master
    paths:
      - docs/**
  pull_request:
    branches:
      - master
    paths:
      - docs/**

jobs:
  linux:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v13
      - name: Build
        id: build
        run: |
          cd docs
          mkdir res
          for f in $(nix-build)
          do
            cp $f/*.pdf res
          done
      - uses: actions/upload-artifact@v2
        with:
          name: docs
          path: docs/res/*.pdf
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "docs_latest"
          # prerelease: true
          title: "Docs"
          files: |
            docs/res/*.pdf
      # - name: Create Release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Changes in this Release
      #       - First Change
      #       - Second Change
      #     draft: false
      #     prerelease: false
